build:
	g++ main.cpp -o main -lGL -lGLU -lglut

test1:
	g++ main.cpp -o main -lGL -lGLU -lglut && ./main -ka 0.2 0.3 0.3 -kd 1 1 0.5 -ks 1 1 1 -sp 30 -pl 5 5 5 0.3 0.3 0.3 -pl -5 -2 5 0.5 0.5 1 -dl 0 1 0 0.5 0.3 0.2

test2:
	g++ main.cpp -o main -lGL -lGLU -lglut && ./main -ka 0.2 0.2 0.2 -kd 1 1 1 -ks 1 1 1 -sp 200 -pl 5 5 5 1 0 0 -pl -5 5 5 0 1 0 -pl -5 -5 5 0 0 1 -pl 0 1 0 1 1 1